<?php include("admin/includes/include.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<?php include("includes/common_script.php"); ?>
<?php
if(file_exists("includes/metatags/meta-".basename($_SERVER['PHP_SELF']))) {
	include("includes/metatags/meta-".basename($_SERVER['PHP_SELF'])); 
} else {
	// ONCE META TAG NOT FOUND USE THE DEFAULT TITLE TAG
	echo '<title>Qmagnets</title>';
}
?>
<style>
.customContentStyle { }
.customContentStyle h3 { margin-bottom:5px; }
.customContentStyle p { line-height:150%; margin-bottom:16px; }
.customContentStyle ol { padding-left:30px; }
.customContentStyle ol li { margin-bottom:5px; }
</style>
</head>
<body>
<div id="main_area">
  <div class="main"> 
    <!--===================start header part===================-->
    <header>
      <div class="header_area">
        <?php include("includes/currency.php");  ?>
        <div class="nav_bg"> 
          <!--====================start nav part====================-->
          <?php include("includes/menu.php");  ?>
          <!--====================start nav part====================-->
           <?php include("includes/search.php");?>
        </div>
         <?php // include("includes/banner.php");  ?>
      </div>
    </header>
    <!--===================end header part===================--> 
    <!--===================Start section part===================-->
    <section>
    <div class="body_area">
         <div class="body_box">
          <div class="body_left_area">
          <div class="body_text_area">
            <div class="body_heading_bg">
              <h1>How Q magnets work</h1>
            </div>
            <div class="about_body_text_box">
				<div id="cse-results" style="display: none;"></div><div class="body_left_text_area customContentStyle" id="static-content">
				
<p>Quadrapolar or Q magnets are unique in that they combine an extremely powerful magnet with a unique patented design that generates <a href="http://www.qmagnets.com/magnetic-field-gradients.php">steep magnetic field gradients</a> to produce the most powerful therapeutic magnet in the world. Q magnet models such as the QF28-6 are able to penetrate up to 50mm (2"), making them ideal for treating both acute and chronic pain. It is a basic principal of physics that common bipolar magnets produce a uniform magnetic field with negligible field gradient. Steep magnetic field gradients are generated by the close interaction of alternating poles as illustrated in the computer generated magnetic field map below. </p>
<p> The research on Quadrapolar magnets can be simplistically summarised as...</p>
<p class="centered"><strong>(Magnet Strength + Magnet Size) X Field Gradient = Therapeutic Effect </strong></p>
<p><img src="images/graphcopy2.jpg" class="imgLeft" width="240" />Where the combination of <strong>Magnet Strength</strong> (measured in Tesla or Gauss) and <strong>Magnet Size</strong> determines the depth of penetration and <strong>Magnetic Field Gradient</strong> is the change in the field strength over distance. The <strong>Therapeutic Effect</strong> is pain relief, reduced inflammation and <a href="http://qmagnets.com/blog/magnetic-therapy-2/debunking-myths-around-magnetic-therapy-and-blood-flow.html">microcirculatory homeostasis</a>. </p>
<p>Like most therapies, be they pharmaceutical or manual, how Q magnets work is not fully understood. However, the evidence suggests that the most likely mechanism of action is that the <a href="magnetic-field-gradients.php">steep field gradients</a> generated by the Quadrapolar magnetic field is altering nerve excitability as a result of changes in membrane permeability to sodium and calcium ions (<a href="magnetic-therapy-relevant-research.php#researchpaper_bems_mclean_1995">McLean et al</a>., 1995 & 1997; <a href="magnetic-therapy-relevant-research.php#researchpaper_bems_cavopol_1995">Cavopol et al</a>., 1995). </p>
<p>The very definition of a magnetic field is that it exerts a force on a moving charged particle. As can be seen from the animation below, a nerve impulse is propagated by the movement of charged particles, mainly Na+ (Sodium), K+ (Potassium) and Ca2+ (Calcium) through the nerve cell membrane. For an illustration, watch the first 60 seconds of the video below:</p>
<div class="centered"><iframe width="480" height="360" src="http://www.youtube.com/embed/U0NpTdge3aw" frameborder="0" allowfullscreen></iframe></div>
<p>Magnetic field gradients were the most important element in the <a href="mri.php">development of the MRI</a>. In fact some 30 years after their initial discovery, Paul Lauterbur and Sir Peter Mansfield won the 2003 Nobel Prize in medicine for resolving how to use magnetic field gradients to generate two dimensional images. Like the period before the discovery of the MRI, most practitioners and observers of magnetic therapy are stuck in the old North and South Pole paradigm, but the science has moved on. </p>
<p>Q magnets have four main applications: </p>
<ol>
<li><strong>Acute Pain</strong> including soft tissue injuries which is from a recent injury such as a muscle tear, bruising, joint sprain or dislocation, a burn, cut or lower back pain from a disc injury or SIJ dysfunction. </li>
<li><strong>Chronic Pain</strong> which persists beyond the expected healing time, often said to be three months such as whiplash, neuralgia, fibromyalgia or lower back pain from a disc injury. </li>
<li><strong>Fracture Healing</strong> for both the pain related to bone fractures and increasing healing times. </li>
<li><strong>Chronic Dysfunction</strong> which is best treated by a health professional experienced in musculoskeletal therapy. </li>
</ol>
<p>The most credible research into magnetic therapy has shown that two things are required to achieve a noticeable therapeutic effect. <strong>Firstly</strong> a magnetic body that is large enough and strong enough to penetrate deep into the body and envelope the target structures such as nerves. <strong>Secondly</strong> you need a <a href="magnetic-field-gradients.php">steep field gradient</a>, the most effective design studied to date is the quadrapolar magnet.</p>
<p>The image below shows a Q magnet as seen through a green magnet viewer:</p>
<p><img src="images/TL09QUADRAPOLE_SINGLE_MAGLINESwebNS.jpg" alt="Q Magnet Model" width="250" class="imgLeft" />The single magnetic body has been magnetised with four alternating quadrants. Looking through the magnet viewer, the boundary between the poles is clearly visible from 6-12 and 3-9. The greatest physiologic effect is achieved when the nerve travels under the length of the boundary, this is why placement is critical for reliable outcomes.</p>
<p>Common bipolar magnets have a uniform magnetic field and negligible field gradient and hence do not share the same therapeutic effect as quadrapolar. Q magnets have achieved both these features while maintaining a small device with our innovative design that is extremely powerful and comfortable to wear. See the available <a href="products.php">Q magnet models</a> and specifications to see which ones are best for your condition.</p>
<p><img src="images/Somerfeld-thigh-comp.jpg" alt="Corked thigh" width="250" class="imgLeft" />The image to the left shows a corked thigh the day after two Q magnets were applied over night. Many professional sports teams and athletes use Q magnets to reduce healing times of injuries such as haematomas (or bruising).</p>
<p>Another common application for Q magnets is placing them over the wisdom teeth nerve root immediately after extraction. In every case we have seen, there has been no pain or swelling post surgery. This observation and the effect on haematomas supports the premise that the therapeutic effect of Q magnets involves <a href="http://qmagnets.com/blog/sceptics/homeopathy-magnetic-therapy-and-placebos-2.html">much more than placebo</a>. </p>
<p>The neurologist who pioneered the use of Quadrapolar magnets, Dr Robert Holcomb used these devices while consulting at Vanderbilt University Medical Centre to successfully treat the most complex pain patients from right across the USA. A number of these <a href="downloads/Qmag_Science.pdf">cases were published in journals such as Pediatric Neurology</a>. TV features of his early work can be <a href="magnetic-therapy-tv.php">viewed on our website</a>. </p>
<p>Magnetic fields are very difficult to conceptualise as they are invisible and as a vector quantity have both magnitude and direction i.e. are positive or negative. One way to observe the flow of magnetic field lines is by sprinkling iron filings over different magnet arrangements. Where the field lines are straight there is very little change and hence negligible gradient as observed with the bipolar magnet in Image A (see below). </p>
<p>Image B shows the original design by Dr Holcomb of four bipolar magnets arranged in a quadrapolar array. Notice the sharp changes in direction of the iron filings near where the magnets touch, the filings follow the field lines and the directional changes indicate the gradient. What the iron filings don't show is the North or South (+ or -) poles such as in the graph above. </p>
<p>Image C shows iron filings sprinkled over the new Q magnet design with a quadrapolar array within one magnetic body. You may notice a more accentuated change of direction in the flow of the iron filings. This is because there is no "wasted space" between the poles that exist with the original design and hence there is a greater interaction between the poles. </p>
<p>Finally Image D is the new <a href="products.php#HF28-6">HF28-6</a> hexapole magnet where you can see the iron filings form around six poles. This shows that there are more active regions in the hexapole model since there are six steep gradient zones instead of four. </p>

<style>
.seps td:first-child { border-right:1px solid #333; }
</style>
<table width="100%" class="tablelist1 seps">

 <tbody>
  <tr>
   <td width="50%"><span>Image A - Bipolar Magnet</span></td>
   <td><span>Image B - Quadrapolar Array</span></td>
  </tr>
  <tr>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="250" height="190" align="absmiddle" title="Bipolar magnet with iron filings">
		<param name="movie" value="/swf/Qmagnets Bipolar.swf" />
		<param name="quality" value="high" />
		<embed src="/swf/Qmagnets Bipolar.swf" width="250" height="190" align="absmiddle" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash"></embed>
		</object>
	</div>
   </td>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="250" height="190" align="absmiddle" title="Bipolar magnet with iron filings">
		<param name="movie" value="/swf/Qmagnets Quad Array.swf" />
		<param name="quality" value="high" />
		<embed src="/swf/Qmagnets Quad Array.swf" width="250" height="190" align="absmiddle" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash"></embed>
		</object>
	</div>
   </td>
  </tr>
  
  <tr>
   <td width="50%"><span>Image C - Quadrapolar Magnet</span></td>
   <td><span>Image D - Hexapolar Magnet</span></td>
  </tr>
  <tr>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="250" height="190" align="absmiddle" title="Bipolar magnet with iron filings">
		<param name="movie" value="/swf/Qmagnets Bipolar.swf" />
		<param name="quality" value="high" />
		<embed src="/swf/Qmagnets ProQ.swf" width="250" height="190" align="absmiddle" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash"></embed>
		</object>
	</div>
   </td>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,28,0" width="250" height="190" align="absmiddle" title="Bipolar magnet with iron filings">
		<param name="movie" value="/swf/Qmagnets Quad Array.swf" />
		<param name="quality" value="high" />
		<embed src="/swf/Qmagnets ProH.swf" width="250" height="190" align="absmiddle" quality="high" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash"></embed>
		</object>
	</div> 
   </td>
  </tr>
  
  <tr>
   <td width="50%"><span>Schematic representation of quadrapole</span></td>
   <td><span>Schematic representation of hexapole</span></td>
  </tr>
  <tr>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<img src="images/Quadrapole.jpg" alt="Schematic representation of hexable" width="250" />
	</div>
   </td>
   <td>
    <div style="text-align:center; padding:16px 0px;">
		<img src="images/Hexapole.jpg" alt="Schematic representation of hexable" width="250" />
	</div>
   </td>
  </tr>
 </tbody>

</table>

<p>At times the effects of using Q magnets are dramatic, as with this Canadian doctor who commented...<br /> "Although I, along with many, cannot be certain as to the precise biological explanation surrounding the physiology of Q magnet action, it is irrefutable in my case that they were, nevertheless, highly effective. For now, we have theories, like so many demonstrable events in nature. These answers may come with further research. Until then, Q magnets are a viable option for pain relief and the possible healing of stress fractures that is simple, effective, and unlike many other remedies, is without complications." <a href="http://qmagnets.com/blog/pain-testimonies/leg-pain/tibia-stress-fracture-threatens-competing-in-marathon-%E2%80%93-no-worries-with-q-magnets.html">Dr Mark R. Thibert, M.D.</a> Plastic Surgeon. </p>
<p>Also many professional sports teams use Q magnets to speed up the recovery after acute injury as commented by the Emerites Western Force Super15 team:<br /> "A number of players have found benefits in helping to resolve muscle haematomas from trauma playing rugby . The players who have used the magnets  believe they have improved a cork by a day or two from the normal healing time. This means they can get back on the training pitch earlier in the week which help their preparation and the teams preparation to perform at the highest level." Rob Naish, Head Physiotherapist. <a href="http://www.rugbywa.com.au/" target="_blank">Emirates Western Force</a>. </p>
<h3>Chronic Pain</h3>
<p>In order to better understand how Q magnets work, one must first understand the mechanism of pain. All pain is first interpreted in the spine. Noxious stimuli such as heat, pressure or chemicals are detected by nociceptors which are sensory nerve receptors found in all tissue (except brain) such as the skin, muscles and joints. </p>
<p>This stimulation is transduced into an electrical signal called an action potential and carried back to the spine. While the perception of pain is filtered through our beliefs, attitudes and behaviours it is also frequency coded and depends on both the number and type of nerve fibres activated and the frequency of the signal. The more nerves that are firing and/or the higher the frequency (i.e. the faster the rate of firing) the greater the perception of pain. There are two types of nociceptors - C-fibres and A-delta fibres. C-fibres are unmyelinated slow conducting nerves that carry impulses at less than one meter per second and are responsible for the dull, burning, aching pain. A-delta are the myelinated fast conducting nerves with impulses travelling at over 15 meters per second and are responsible for sharp pain. </p>
<p>Essentially your A-delta fibres carry the sharp immediate pain perception to the spine and it’s usually immediately returned with a withdrawal reflex action. After this the C-fibres take over with that slow dull ache that I am sure you have experienced. Tissue damage produces an “inflammatory soup” with the release of pain chemicals such as prostaglandins. The pain persists because these pain-mediating chemicals linger and make the nerve more sensitive to further stimulation. </p>
<p>A common treatment to combat inflammation pain is to take anti-inflammatory drugs that in turn reduces the production of prostaglandins. The best-known anti-inflammatory drug is Aspirin. For more severe chronic pain the use of opioids such as morphine seem to be the treatment of choice. The side effects of using these drugs long term is one of the greatest concerns of pain sufferers. Q magnets are a one off purchase, have no side effects (unless you have a pacemaker or some other type of implanted electrical device) and target only the area that it's applied. </p>
<p>Much of the early research on Quadrapolar magnets was pioneered by neurologists Dr Robert Holcomb and Dr Mike McLean while associate professors of neurology at Vanderbilt Medical University. Here they harvested live nerve ganglions from patients undergoing back surgery (with their permission of course) and exposed them to a variety of static magnetic fields. What they found was remarkable, when they exposed the nerve cell to a steep field gradient such as is generated by a Q magnet, the nerve impulse or action potential was completely blocked. The action potential is a self generating wave that carries the nerve signal, such as pain along the nerve to the brain and can be seen in the diagram below. They even exposed nerve cells to the noxious stimuli capsaicin which got the sensory neurons really firing, but after 5 minutes of exposure to the gradient of the Quadrapolar array, the signal was totally blocked and fully recovered 10 minutes after the removal of the field. This research was published in - "Static Magnetic Fields for the Treatment of Pain". McLean et al. <a href="magnetic-therapy-relevant-research.php#researchpaper_eb_mclean_2001">Epilepsy & Behavior2: S74-S80 (2001)</a>;</p>
<p><img src="images/image013.jpg" alt="Statistics" width="560" /></p>
<p>Essentially the steep field gradient blocks the firing of the action potential even with increased stimulus after a few minutes and is reversible after removal. This effect occurs mostly on the unmyelinated, slow conducting C-fibre nerves and to a much lesser degree on the myelinated, fast conducting A-Delta nerves. </p>
<p>Once you have a basic understanding of how pain works and how multipolar static magnets that generate steep field gradients work, it’s not difficult to bring it together into a working theory for the application of static magnets in the treatment of pain. The steep field gradients work mostly on interrupting the firing of the unmyelinated C-fibres. This is why they are so effective at blocking the dull aching pain, but have little effect on the sharp reflex pain. </p>
<p>More health professionals are adopting this technology as it’s quick and simple to apply and there are no side effects. As more research is conducted, more clinically reliable outcomes are achieved. This is one of the major reasons doctors prescribe pain relieving drugs. While they might have side effects, they are reasonably reliable but not in all cases. Take this <a href="http://www.qmagnets.com/blog/pain-testimonies/tmj-pain/my-daughter-is-currently-pain-free-after-having-suffered-excruciating-and-constant-pain-for-over-a-year.html">case of trigeminal neuralgia</a>, the patient was referred to purchase Q magnets by her neurologist. She had severe and debilitating pain through the jaw for over a year that was not responding to drug therapy. After applying a Q magnet for two days, her pain was gone and in many months since has not returned. Q magnets seem to be very effective with MS induced neuralgia pain as the condition causes demyelination of the nerves. </p>
<p>More and more <a href="http://www.qmagnets.com/blog/category/sport">professional sports</a> people use Q magnets as <a href="http://qmagnets.com/blog/condition-testimonies/bruises/recover-faster-after-bruisinghaematoma-and-soft-tissue-injuries-with-q-magnet-therapy.html">self-management therapy</a>. Pprofessional sports teams are usually at the cutting edge of rehabilitation because one missed game for a key player can have huge implications. Some of the treatments used by professional athletes such as injecting stem cells to regenerate cartilage can be very expensive and probably not realistic for the average population who are more than likely better off simply taking a few more weeks with restricted duties rather than spend the tens of thousands of dollars for expensive interventions.</p>
<p>However the cost of a few hundred dollars for the purchase of a set of Q magnets that will last for decades becomes financially viable and clinically relevant. </p>
<p class="centered">Click on the Order Now button below to place your order. </p>
<p class="centered"><a href="products.php"><img src="images/order-now-button.gif" alt="Order Now!" /></a></p>
				
				</div>
             </div>
            <div class="left_bottom_img"><img src="images/body_left_bottom_img.jpg" alt="" border="0"></div>
            </div>
          </div>
          
          <div class="body_right_area">
          <?php include("includes/yourpain.php");  ?>
          <?php include("includes/blog.php");      ?>
          </div>
        </div>
        </div>
    </section>
    <!--===================end section part===================--> 
    <!--===================Start footer part===================-->
    <footer>
      <?php include("includes/footer.php"); ?>
    </footer>
    <!--===================end footer part===================--> 
  </div>
</div>
</body>
</html>

