<?php include("admin/includes/include.php");  ?>

<!DOCTYPE HTML>
<html>
<head>
<?php include("includes/common_script.php"); ?>
</head>
<body>
<div id="main_area">
  <div class="main"> 
    <!--===================start header part===================-->
    <header>
      <div class="header_area">
         <?php include("includes/currency.php");  ?>
        <div class="nav_bg"> 
          <!--====================start nav part====================-->
          <?php include("includes/menu.php");  ?>
          <!--====================start nav part====================-->
          <?php include("includes/search.php");?>
        </div>
        <?php include("includes/banner.php");  ?>
      </div>
    </header>
    <!--===================end header part===================--> 
    <!--===================Start section part===================-->
    <section>
    <div class="body_area">
        <div class="body_box">
          <div class="body_left_area">
          <div class="body_text_area">
            <div class="body_heading_bg">
              <h1>How Q magnets work</h1>
            </div>
            <div class="about_body_text_box">
              <div class="how_body_left_text_area">The image below shows a Q magnet as seen through a green magnet viewer:

<br><br>
                <div id="body_img"><img src="images/how_img1.jpg" alt="" width="221" height="160" border="0"></div>
                Where the combination of Magnet Strength (measured in Tesla or Gauss) and Magnet Size determines the depth of penetration and Magnetic Field Gradient is the change in the field strength over distance. The Therapeutic Effect is pain relief, reduced inflammation and microcirculatory homeostasis.<br><br>

 Like most therapies, be they pharmaceutical or manual, how Q magnets work is not fully understood. However, the evidence suggests that the most likely mechanism of action is that the steep field gradients generated by the Quadrapolar magnetic field is altering nerve excitability as a result of changes in membrane permeability to sodium and calcium ions (McLean et al., 1995 & 1997; Cavopol et al., 1995).</div>
 <div class="how_body_left_text_area">
   The image below shows a Q magnet as seen through a green magnet viewer:<br><br>
                <div id="body_img"><img src="images/how_img2.jpg" alt="" width="221" height="160" border="0"></div>
                The single magnetic body has been magnetised with four alternating quadrants. Looking through the magnet viewer, the boundary between the poles is clearly visible from 6-12 and 3-9. The greatest physiologic effect is achieved when the nerve travels under the length of the boundary, this is why placement is critical for reliable outcomes.
Common bipolar magnets have a uniform magnetic field and negligible field gradient and hence do not share the same therapeutic effect as quadrapolar. Q magnets have achieved both these features while maintaining a small device with our innovative design that is extremely powerful and comfortable to wear.</div>
<div class="how_body_left_text_area">
   <h2>WHAT ARE THE EFFECTS?</h2> <br>
                <div id="body_img"><img src="images/how_img3.jpg" alt="" width="221" height="160" border="0"></div>
                The image to the left shows a corked thigh the day after two Q magnets were applied over night. Many professional sports teams and athletes use Q magnets to reduce healing times of injuries such as haematomas (or bruising).<br><br>

 Another common application for Q magnets is placing them over the wisdom teeth nerve root immediately after extraction. In every case we have seen, there has been no pain or swelling post surgery. This observation and the effect on haematomas supports the premise that the therapeutic effect of Q magnets involves much more than placebo.</div>
 <div class="how_img_box_area">
 <div class="how_img_con">
 <div class="how_img_area">
  <div class="how_img_heading">Image A - Bipolar Magnet</div>
  <div class="how_img_box"><img src="images/how_img4.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 <div class="how_img_area1">
  <div class="how_img_heading1">Image B - Quadrapolar Array</div>
  <div class="how_img_box"><img src="images/how_img5.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 </div>
 <div class="how_img_con">
 <div class="how_img_area">
  <div class="how_img_heading">Image C - Quadrapolar Magnet</div>
  <div class="how_img_box"><img src="images/how_img6.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 <div class="how_img_area1">
  <div class="how_img_heading1"> Image D - Hexapolar Magnet</div>
  <div class="how_img_box"><img src="images/how_img7.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 </div>
 <div class="how_img_con">
 <div class="how_img_area">
  <div class="how_img_heading">Schematic representation 
of quadrapole</div>
  <div class="how_img_box"><img src="images/how_img5.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 <div class="how_img_area1">
  <div class="how_img_heading1">Schematic representation of 
hexapole</div>
  <div class="how_img_box"><img src="images/how_img6.jpg" alt="" width="221" height="160" border="0"></div>
 </div>
 </div>
 </div>
 At times the effects of using Q magnets are dramatic, as with this Canadian doctor who commented...
"Although I, along with many, cannot be certain as to the precise biological explanation surrounding the physiology of Q magnet action, it is irrefutable in my case that they were, nevertheless, highly effective. For now, we have theories, like so many demonstrable events in nature. These answers may come with further research. Until then, Q magnets are a viable option for pain relief and the possible healing of stress fractures that is simple, effective, and unlike many other remedies, is without complications." Dr Mark R. Thibert, M.D. Plastic Surgeon.
             </div>
            <div class="left_bottom_img"><img src="images/body_left_bottom_img.jpg" alt="" border="0"></div>
            </div>
          </div>
          
          <div class="body_right_area">
          <?php include("includes/yourpain.php");  ?>
            <?php include("includes/blog.php"); ?>
          </div>
        </div>
        </div>
    </section>
    <!--===================end section part===================--> 
    <!--===================Start footer part===================-->
    <footer>
      <?php include("includes/footer.php"); ?>
    </footer>
    <!--===================end footer part===================--> 
  </div>
</div>
</body>
</html>
