<?php include("admin/includes/include.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<?php include("includes/common_script.php"); ?>
<?php
if(file_exists("includes/metatags/meta-".basename($_SERVER['PHP_SELF']))) {
	include("includes/metatags/meta-".basename($_SERVER['PHP_SELF'])); 
} else {
	// ONCE META TAG NOT FOUND USE THE DEFAULT TITLE TAG
	echo '<title>Qmagnets</title>';
}
?>
<style>
.customContentStyle { }
.customContentStyle h3 { margin-bottom:5px; }
.customContentStyle p { line-height:150%; margin-bottom:16px; }
.customContentStyle ol { padding-left:30px; margin-bottom:20px; }
.customContentStyle ol li { margin-bottom:5px; }
</style>
</head>
<body>
<div id="main_area">
  <div class="main"> 
    <!--===================start header part===================-->
    <header>
      <div class="header_area">
        <?php include("includes/currency.php");  ?>
        <div class="nav_bg"> 
          <!--====================start nav part====================-->
          <?php include("includes/menu.php");  ?>
          <!--====================start nav part====================-->
           <?php include("includes/search.php");?>
        </div>
         <?php // include("includes/banner.php");  ?>
      </div>
    </header>
    <!--===================end header part===================--> 
    <!--===================Start section part===================-->
    <section>
    <div class="body_area">
         <div class="body_box">
          <div class="body_left_area">
          <div class="body_text_area">
            <div class="body_heading_bg_big">
              <h1>Published Research on Magnetic Therapy Relevant to Q magnets</h1>
            </div>
            <div class="about_body_text_box">
				<div id="cse-results" style="display: none;"></div><div class="body_left_text_area customContentStyle" id="static-content">
				
<p>Evidence-based practice is the integration of clinical expertise and systematic research from clinical trials and basic sciences. While it is clear that much more research needs to be undertaken into neuromagnetics, comments such as "there is no evidence to support the use of magnetic therapy in clinical practice" shows a misunderstanding or high degree of ignorance on the topic. Since 1990, many thousands of patients have been successfully treated by experienced health professionals such as physicians, neurologists, physiotherapists and chiropractors. </p>
<p>Q magnets produce an inhomogeneous magnetic field and are used by placing them directly over the pain or the nerves that innervate that area including the spinal cord. Below we provide published research that investigates the use of multipolar magnets, i.e. magnets that produce a field gradient (inhomogeneous field) over the area of pain. An image of the magnetic pattern or orientation of the active device is shown for each study.</p>

<h3> The following studies are organised into 5 categories:</h3>
<ol style="text-align:left">
<li><a href="#RCTs">Randomised Controlled Trials, i.e.  comparing efficacy of an active magnet device with a  non-active placebo. </a></li>
<li><a href="#CSs">Case Studies.</a></li>
<li><a href="#Rs">Reviews of the literature on magnetic therapy.</a></li>
<li><a href="#ASs">Animal studies</a></li>
<li><a href="#CSBSs">Cell studies and basic sciences. </a></li>
</ol>

<h3><a name="RCTs" id="RCTs"></a>RANDOMISED CONTROLLED TRIALS:</h3>
<strong>RCT1</strong>
<p><a name="Holcomb1991" id="Holcomb1991"></a><a href="downloads/pub-bio-1.pdf" target="_blank">Holcomb et al. (1991)</a> in a multicentre randomized crossover  study on 54 subjects with chronic low back or knee pain.  The placebo was non-magnetic and the active  device was an inhomogeneous 200 mT (2000G) quadrapolar array.</p>
<p><img src="images/clip_image002.jpg" alt="Magnetic device" class="imgLeft" width="260" />The magnetic devices were worn for 24 hours with a seven day washout period.  Holcomb et al (1991) reported a significant reduction in low back and knee pain at 1 and 24 hours but not at 3 hours.</p>

<p>There was also an increased used of analgesia <a href="#Laakso-et-al-Static-Magnets-What-are-they-and-what-do-they-do">(Laakso et al, 2009)</a>.  Unfortunately this  article has not been peer reviewed and efficacy of blinding and low subject  numbers are questioned along with heterogeneity of diagnosis (some subjects had both  back and knee pain (<a href="#Laakso-et-al-Static-Magnets-What-are-they-and-what-do-they-do">Laakso et al, 2009</a>).</p>
<p><a href="downloads/pub-bio-1.pdf" target="_blank">Holcomb RR, Parker RA, Harrison MS</a>. Biomagnetics in the treatment of human pain-past, present, future. <em>Environ Med. 1991;8:24-30</em>.</p>

<strong>RCT2</strong>
<p><a name="researchpaper_apmr_segal_2001" id="researchpaper_apmr_segal_2001"></a><a href="downloads/Pub-Knee.pdf" target="_blank">Segal et al. (2001)</a> studied 64 patients with Rheumatoid  Arthritis who suffered moderate knee pain by application of 190 mT (1900 gauss) quadrapolar magnets and  a placebo which was a  weak standard bipolar magnet with a a homogeneous  field of strength 72 mT (720 gauss). </p>
<p>Subjects randomly assigned to the quadrapolar magnet group showed a greater reduction in joint pain than did the control group after one week follow up (40.4% vs 25.9%) and twice daily pain diary results (p, 0.0001) for each vs <img src="images/clip_image002.jpg" alt="Magnetic device" class="imgLeft" width="255" />baseline.  Quadrapolar ArrayHowever, comparison between the two groups demonstrated no statistical significance (p<.23).  Subjects in the quadrapolar magnet group reported an average decrease in the global assessment of the disease activity of 33% over one week, as compared with a 2% decline in the control group (p<0.01).  </p>
<p>After one week, 68% of the quadrapolar magnet treatment group reported feeling better compared with 27% of the control group.  Whilst 29% of the active group and 65% of the placebo group reported feeling the same as before treatment (p<0.01) and Segal et al (2001) concluded that both devices demonstrated statistically significant pain reduction compared to baseline.  However, a significant difference was not observed between the two treatment groups (p<0.23).   </p>
<p>Segal et al (2001) recommended that a nonmagnetic placebo treatment be used to characterize further its therapeutic potential for treating rheumatoid arthritis.</p>
<p><a href="downloads/Pub-Knee.pdf" target="_blank">Segal, N.A., Toda, Y., et al. (2001)</a>. Two configurations of static magnetic fields for treating rheumatoid arthritis of the knee: a double-blind clinical trial. <em>Arch Phys Med Rehabil: 2001 Oct;82(10):1453-60</em>;<span class="style2">.</span> <a href="http://www.ncbi.nlm.nih.gov/pubmed/11588753" target="_blank">PMID: 11588753</a>; <a href="http://dx.doi.org/10.1053%2Fapmr.2001.24309" target="_blank">doi.</a></p>

<strong>RCT3</strong>
<p><a name="Constantino" id="Constantino"></a><a href="downloads/Constantino-et-al-Treatment-of-wrist-and-hand-fractures-with-natural-magnets.pdf" target="_blank">Costantino et al. (2007)</a> studied 40 patients  with wrist fractures after applying a Quadrapolar array of 12,500G (internal Gauss  rating) directly over the fracture  in the plaster cast of the subjects.  Resulting in bone callus formation that produced a  35% improvement in healing rates compared to ‘standard’ time.   </p>
<img src="images/clip_image002.jpg" alt="Magnetic therapy" width="250" />
<p><a href="downloads/Constantino-et-al-Treatment-of-wrist-and-hand-fractures-with-natural-magnets.pdf" target="_blank">Costantino C., et al. (2007)</a>. Treatment  of wrist and hand fractures with natural magnets: preliminary report. <em>Acta Bio  Medica. 2007;78:198-203</em>; <a href="http://www.ncbi.nlm.nih.gov/pubmed/18330079" target="_blank">PMID: 18330079</a>.</p>
 
<strong>RCT4</strong>
<p><a name="Vallbona" id="Vallbona"></a><a href="http://www.cebp.nl/media/m1101.pdf" target="_blank">Vallbona et al. (1997)</a> studied 50 patients who were diagnosed  with post polio syndrome who reported muscular or arthritic-like pain.  The double-blind randomized clinical trial  with application of active (300 to 500 gauss) inhomogeneous magnetic devices to  the affected area for 45 minutes.  From a  description of the active devices with a pattern of concentrically arranged  circles of alternating magnet polarity and the manufacturer’s 1985 patent  number 4,549,532, the field patterns were orientated as in the following  diagram. </p>
<p><img src="images/clip_image003_001.jpg" class="imgLeft" width="250" alt="Outcome messures" />Outcome measures were scored using the Mc Gill Pain Questionnaire.  The results of the patients using the placebo devices experienced a decrease of 1.1 ± 1.6 points (p<0.005) on a 10 point scale while the active group a decrease of 5.2 ± 3.2 (p<0.0001). </p>
<p><strong>Those who received the active device reported much less pain than those who had the inactive device.</strong></p>
<p>The proportion of patients in the active-device group who reported a pain score decrease greater than the average placebo effect was 76%, compared with 19% in the placebo-device group (p< .0001).  Vallbona concluded the application of a static magnetic field of 300-500 gauss over a trigger point offers significant and prompt relief of trigger point pain in post polio subjects.</p>
<p><a href="https://www.cebp.nl/media/m1101.pdf" target="_blank">Vallbona C., Hazelwood C.F., et al. (1997)</a>. Response of pain to  static magnetic fields in postpolio patients: a double-blind pilot study. <em>Arch  Phys Med Rehabil. 1997;78(11):1200-3</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/9365349" target="_blank">PMID: 9365349</a>; <a href="http://dx.doi.org/10.1016%2FS0003-9993%2897%2990332-4" target="_blank">doi</a>.</p>

<strong>RCT5</strong>
<p><a name="Kovacs-Balint" id="Kovacs-Balint"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/21225890" target="_blank">Kovacs-Balint et al. (2011)</a> used previous research with animal studies such as <a href="#researchpaper_bems_laszlo_2007">Laszlo et  al</a>, (2007)  and Sandor et al, (2007)  on optimized inhomogeneous static magnetic fields to induce analgesia. A  similar inhomogeneous static magnetic field (iSMF) was used to investigate the  attenuating effects of iSMF on the thermal pain threshold (TPT) in healthy  young adults in a double-blind, placebo controlled manner. </p>
<p> The finger tips of 15 healthy subjects were exposed to the iSMF with a maximum gradient of 13.2 T/m for 30 minutes. TPT and VAS data were recorded at 0, 15 and 30min exposure time. There were three blocks, iSMF, sham and the control and after each block subjects used the VAS to rate the pain.  </p>
<p>It was demonstrated that exposure to iSMF significantly increases pain threshold (measured in °C). VAS profiles indicated an ongoing increase in pain ratings between measurement blocks in the sham condition, while remaining at a constant level in the genuine condition. </p>
<p><a href="http://www.ncbi.nlm.nih.gov/pubmed/21225890" target="_blank">Kovacs-Balint,  Z.,  Csatho, A., et al. (2011)</a>. &quot;Exposure to an inhomogeneous static  magnetic field increases thermal pain threshold in healthy human  volunteers.&quot; <u><em>Bioelectromagnetics</em></u><em> 2011;<strong>32</strong>(2): 131-139</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/21225890" target="_blank">PMID: 21225890</a>;<a href="http://dx.doi.org/10.1002%2Fbem.20622" target="_blank"> doi</a>.</p>

<strong>RCT6</strong>
<p><a name="Laszlo" id="Laszlo"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/22288770" target="_blank">Laszlo et al. (2012)</a> studied 79 adult patients with temporomandibular disorders, alveolitis and aphtha in a randomised controled trial. The active static magnet arrangement produced and inhomogeneous magnetic field with a 0-192 mT peak to peak induction with a 19 T/m lateral gradient at 3mm from the magnet. </p>
<p>Static magnetic field exposure of the active group significantly reduced pain perception (reduction from baseline to post-treatment VAS score) in the group with temporomandibular disorders from 2.0 ± 0.3 versus  0.5 ± 0.1 (n = 29, p = 0.0003. </p>
<p><a href="http://www.ncbi.nlm.nih.gov/pubmed/22288770" target="_blank">Laszlo, J., et al. (2012)</a> “Effect of local exposure to inhomogeneous static magnetic field on stomatological pain sensation - a double-blind, randomized, placebo-controlled study.” <em>Int J Radiat Biol. 2012 Feb 28</em><br />
<a href="http://www.ncbi.nlm.nih.gov/pubmed/22288770" target="_blank">PMID: 22288770</a>; <a href="http://dx.doi.org/10.3109%2F09553002.2012.661916" target="_blank">doi</a>. </p>

<strong>RCT7</strong>
<p> Hermans et al. (2011) conducted a pilot trial investigating the effect and effect mechanisms of neuromagnetics treatment i.e. an inhomogeneous static magnetic field, on osteoarthritis of the knee. This was a pilot RCT with 5 subjects completing the trial.</p>
<p>The aim of this study was to examine how the quadrapolar magnets modified the pain response in osteoarthritis of the knee.  Although the participant numbers were small, the results demonstrated that there was a non significant downward trend in VAS pain scores as recorded in the participant’s pain diaries.</p>
<p> Quadrapolar rating The active device was a Quadrapolar magnet with internal gauss rating of 13,500 Gauss and equivalent to the QF28-6. Patients were randomly assigned to a week of treatment with an active device or a week with the non-active placebo (control). After the first week, there was a one week washout with no device and then a week with the alternative treatment. Hence a subject starting with one week of the active device, would then have a week break with no device and then a week with the placebo device and vice versa. </p>
<p> Sympathetic nervous system (SNS) pathways such as skin temperature, blood flux and skin conductance were measured immediately before and after application of the devices.   Pain scores were measured using WOMAC, the functional squat and VAS (Visual Analogue Scale pain scores) were recorded in a pain diary. </p>
<p> There was no statistical difference in SNS measures between the groups. The descending inhibitory system (through the SNS) is unlikely to be involved in the mechanism of pain relief mediated by static magnetic fields.</p>
<p>The following graph illustrates the mean pain per day for all participants as recorded in a pain diary. There was an upward trend in pain scores during the washout period and improved pain scores were greater with the active magnets than for placebo. </p>
<p><img src="images/VAS-Compare-web.jpg" width="560" alt="Figure 4.5" /></p>
<p>The trial provided evidence suggesting that further research is warranted with greater participant numbers. Yet to be published.</p>

<strong>RCT8</strong>
<p><a name="Weintraub2003" id="Weintraub2003"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/12736891" target="_blank">Weintraub et al. (2003)</a> conducted a multicentre (48 centres in 27 USA states) to  assess if 450 gauss multipolar insoles could affect the pain of diabetic  peripheral neuropathy. The field generated by the insoles was inhomogeneous as  can be seen from the manufactures (<a href="nikken.php">Nikken</a>) 1999 patent # 5,871,438.</p>
<p><img src="images/clip_image002_002.jpg" width="250" class="imgLeft" />375 subjects were recruited with symptomatic bilateral sensory and motor neuropathy who were randomly selected to wear either the magnetic or placebo insoles for 4 months (24 hours per day).  Symptoms had to be constant and present for at least 6 months and to be 6 months without pain medications.  </p>
<p>On assessment of bias and masking there was no significant association between the actual treatment and the placebo from both subjects and investigators.  There was significant difference in the third and fourth month in burning, (mean change for magnet treatment, -12%; for sham, -3%; p<0.05 ANCOVA) numbness and tingling, (magnet,-10%; sham, +1%; p<0.05 ANCOVA) and exercise induced foot pain (Magnet, -12%; sham, -4%; p<0.05, ANCOVA). </p>
<p>Weintraub et al (2003) with a subset of patients with baseline severe pain, statistically significant reductions occurred from baseline through the fourth month in numbness and tingling (magnet, -32%; sham, -14%; p< 0.01 ANOVA).  Weintraub et al (2003) concluded that static magnetic fields can penetrate up to 20 mm and appear to target the ectopic firing nociceptors in the dermis and epidermis.  Over time it is recommended by Weintraub et al (2003) that analgesic benefits occur. </p>
<p>In a study published in JAMA, <a href="#Collacott">Collacott</a> used a similar but slightly weaker rubber magnet for the treatment of lower back pain but the lack of depth of penetration was most likely the determining factor in the poor outcomes achieved. </p>
<p><a href="http://prdupl02.ynet.co.il/ForumFiles_2/25923990.pdf" target="_blank">Weintraub, M.I., Wolfe, G.I.,  et al. (2003)</a>. &quot;Static magnetic field therapy for symptomatic diabetic neuropathy: a  randomized, double-blind, placebo-controlled trial.&quot; <em>Arch Phys Med Rehabil.  2003;84(5):736-46</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12736891" target="_blank">PMID: 12736891</a>; <a href="http://dx.doi.org/10.1016%2FS0003-9993%2803%2900106-0" target="_blank">doi</a>.</p>


<strong>RCT9</strong>
<p><a name="Weintraub1999" id="Weintraub1999"></a>Weintraub et al. (1999) in a randomized double- placebo, crossover  study assessed 19 subjects using 475 gauss inhomogeneous insoles using a sham  and active magnets. The field  generated by the insoles was inhomogeneous as can be seen from the manufactures  (<a href="nikken.php">Nikken</a>) 1996 patent # 5,538,495.</p>
<p><img src="images/clip_image002_001.jpg" width="250" class="imgLeft" />The devices were worn for 24 hours per day for 30 days for each phase of trial with a total treatment time of 12 weeks.  Weintraub et al (1999) significantly reduced burning pain, tingling and numbness in diabetic group using VAS as measurements.  </p>
<p>The limitations of the trial was a lack of double blind component, small size; heterogeneity of subject diagnoses and no wash out period between active and sham episodes.</p>
<p>Weintraub, M.I., et al. (1999). Magnetic Bio-Stimulation in painful diabetic peripheral neuropathy: a novel intervention – a randomized, double-placebo, crossover study. American Journal of Pain Management. 1999;9:8-17. </p>

<strong>RCT10</strong>
<p><a name="Brown" id="Brown"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/12501067" target="_blank">Brown et al. (2002)</a> studied 32 patients with Chronic Pelvic  Pain by measuring pain relief and disability over two weeks and 19 patients  completed 4 weeks of randomized double-blind placebo-controlled treatment at a  gynaecology clinic.  Assessment was made  using McGill Pain Questionnaire, Pain Disability Index and Clinical Global  Impressions Scale were outcome measures.  </p>
<p>The results of patients receiving active inhomogeneous (500 gauss) or sham placebo magnets were applied to abdominal trigger points for 24 hours per day. From a description of the active devices with a concentric bipolar configuration and the manufacturer’s 1985 patent number 4,549,532, the field patterns were orientated as in the following diagram.</p>
<p><img src="images/clip_image003_001.jpg" class="imgLeft" width="250" />The patients receiving the active magnets who completed four weeks of double-blind treatment had significantly lower Pain Disability Index (p<0.05),  Clinical Global Impressions – Severity (p<0.05) and Clinical Global impressions – Improvement (p<0.01) scores than those receiving placebo magnets, yet were more likely to correctly identify their treatment (p<0.05).  </p>
<p>Brown et al (2002) concluded that Static Magnetic Field (SMF) therapy significantly improves disability and may reduce pain when active magnets are worn continuously for four weeks in patients with Chronic Pelvic Pain.</p>
<p><a href="http://www.ncbi.nlm.nih.gov/pubmed/12501067" target="_blank">Brown, C.S., Ling, F.W., Wan, J.Y., et al. (2002)</a>. Efficacy of static  magnetic field therapy in chronic pelvic pain: a double-blind pilot study. <em>Am J  Obstet Gynecol 2002;187:1581-7</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12501067" target="_blank">PMID: 12501067</a>; <a href="http://dx.doi.org/10.1067%2Fmob.2002.128026" target="_blank">doi</a>.</p>

<strong>RCT11</strong>
<p><a name="Collacott" id="Collacott"></a><a href="http://jama.ama-assn.org/content/283/10/1322.full.pdf+html" target="_blank">Collacott et al. (2000)</a> in a randomized, double blind,  placebo controlled crossover pilot study with a sample of male/female chronic  degenerative low back pain with 20 subjects.   The active inhomogeneous magnet with 30mT (300gauss) was worn for six  hours per day for three days per week for one week for a total of 18 hours for  both demagnetized sham and magnetic devices. The field generated by the insoles  was inhomogeneous as can be seen from the manufactures (<a href="nikken.php">Nikken</a>) 1996 patent #  5,538,495. </p>
<p><img src="images/clip_image002_001.jpg" class="imgLeft" width="250" />The study applied a placebo sham with a result of no pain relief or increase in range of motion (VAS and Pain Rating Index).  The limitations of the study is that it is a small sample size, there is a lack of gender equality (males= 19 and females = 1).  The range of pathologies for diagnosis of Low Back Pain and uncertain success of subject blinding (Laakso et al, 2009)</p>
<p>What is amusing about this study is how often it is quoted by sceptics as proof that magnetic therapy does not work. However the 300G magnets used would barely penetrate 12mm (1/2 inch), which when considering the spinal cord at the lower back level is around 50mm (2 inches) away from the skin's surface would explain why this study proved no efficacy. </p>	
<p>Even the authors made the statement...Our results did not support the findings of Vallbona et al and Weintraub (see above). However, there were considerable differences in the study designs and populations, including the cause of pain. The patients of Vallbona and colleagues had muscle pain while Weintraub’s subjects had neuropathic pain. The source of pain in our participants would appear to be deeper than that of the former, and may explain the lack of beneficial effect from the magnets used (300 G).</p>
<p><a href="http://jama.ama-assn.org/content/283/10/1322.full.pdf+html" target="_blank">Collacott, E.A., Zimmerman, J.T., et al. (2000)</a>.  Bipolar  permanent magnets for the treatment of chronic low back pain. <em>JAMA.  2000;283(10):1322-5</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/10714732" target="_blank">PMID: 10714732</a>; <a href="http://dx.doi.org/10.1001%2Fjama.283.10.1322" target="_blank">doi</a>.</p>

<strong>RCT12</strong>
<p><a name="Cepeda" id="Cepeda"></a><a href="downloads/StaticMagneticTherapyDoesNotDecreasePainorOpioidRequirements.pdf">Cepeda et al. (2007) </a> chose  quadrapolar static magnets for this study but  unfortunately the methodology was flawed.  Health professionals experienced with using quadrapolar magnets  know that after  surgery, you place the magnets directly over the wound incision, over the dressing of course. The image below shows where the magnets were applied for this study. </p>
<p><img src="images/surgicalwound.jpg" alt="Magnet placement around abdomen surgical wound" width="239" height="211" align="left" class="imgLeft" />As shown in the diagram, the  magnets were placed around the incision and none over the wound. In fact, very few  are even close to the recommended<a href="abdominalpain.php"> treatment protocol for abdominal pain</a>.</p>
<p>Unlike drugs that anesthetists use, the physiological effect of magnets is very specific and localised. The intensity of a static magnetic field diminishes in proportion to the inverse of the cube of the distance. Correct placement of Q magnets to effect nerve tissue, pain and inflammation is vital in order to achieve a successful outcome. Placements out by as little as 1cm or 1/2 inch will likely achieve a poor clinical outcome.</p>
<p>This study was never going to achieve a successful outcome for magnetic therapy because of its poor design. See a review of another study using magnetic therapy for post operative pain that did show significant improvement <a href="blog/condition-testimonies/bruises/recover-faster-after-bruisinghaematoma-and-soft-tissue-injuries-with-q-magnet-therapy.html">here</a>. </p>
<p><a href="downloads/StaticMagneticTherapyDoesNotDecreasePainorOpioidRequirements.pdf">Cepeda, M., et al (2007).</a> Static Magnetic Therapy does not decrease pain or opioid requirements: A randomized double-blind trial. <em>Anesth &amp; Analg 2007;104:290-294</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17242082" target="_blank">PMID: 17242082</a>; <a href="http://dx.doi.org/10.1213/01.ane.0000230613.25754.08" target="_blank">doi</a></p>

<strong>RCT13</strong>
<p><a name="Man" id="Man"></a><a href="blog/condition-testimonies/bruises/recover-faster-after-bruisinghaematoma-and-soft-tissue-injuries-with-q-magnet-therapy.html" target="_blank">Man et al. (1999)</a> randomly  assingned 10 patients to an active magnet group and 10 to a placebo group to assess the effects of a permanent static magnetic field on wound healing after liposuction. </p>
<p> The magnet is not well described other than there were multiple ceramic magnets inserted into patches such that the surface strength was between 150 and 400 gauss (15-40 mT) all orrientated with the negative pole to the body. </p>
<p> The results showed that the treatment group had significant reductions in pain on postoperative days 1 through 7, in edema on days 1 through 4 and discolouration on days 1 through 3 when compared to the contol group. </p>	
<p>The study concluded that the magnetic field from the active magnet group was quite remarkable in both the prevention and treatment of these signs and symptoms and also in the alleviation of pain itself. The magnitute of the reduction in postoperartive pain was quite significant, allowing for a decrease in the need for analgesic medication. For a more comprehensive review see <a href="blog/condition-testimonies/bruises/recover-faster-after-bruisinghaematoma-and-soft-tissue-injuries-with-q-magnet-therapy.html">recover faster from soft tissue injuries</a>. </p>
<p><a href="http://www.ncbi.nlm.nih.gov/pubmed/11149796" target="_blank">Man, D., et al. (1999)</a>. The influence of permanent magnetic field therapy on wound healing in suction lipectomy patients: a double-blind study. <em>Plast Reconstr Surg Dec;104(7):2261-6</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/11149796" target="_blank">PMID: 11149796</a>; <a href="http://dx.doi.org/10.1097/00006534-199912000-00051" target="_blank">doi</a>.</p>

<div style="text-align:left;">

	<h3><a name="CSs" id="CSs"></a>CASE STUDIES:</h3>
	<p>Abdominal &amp; Genital Pain<br /><a name="Holcomb" id="Holcomb"></a><a href="downloads/Qmag_Science.pdf" target="_blank">Holcomb et al. (2000)</a> reviewed the cases of two adolescent with debilitating,  medication-resistant chronic pain of the low back and abdomen who had undergone  multiple evaluations and interventions by medical specialists. Both cases were  treated with multiple alternating quadrapolar array magnet devices made from  rare earth magnets. Both were provided rapid relief (within minutes) which was  sustained for more than two years. </p>
	<p><a href="downloads/Qmag_Science.pdf" target="_blank">Holcomb, R.R., Worthington, W.B., McCullough, B.A., McLean, M.J</a>. Static  magnetic field therapy for pain in the abdomen and genitals. <em>Pediatr Neurol.  2000;2(3)3:261-4</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/11033291" target="_blank">PMID: 11033291</a>; <a href="http://dx.doi.org/10.1016%2FS0887-8994%2800%2900180-6" target="_blank">doi</a>.</p>
	<p><a name="Panagos" id="Panagos"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/15162885" target="_blank">Panagos et al. (2004)</a> in a case series in a university  hospital assessed eight participants with myofascial shoulder pain in the  spinal cord injured population using inhomogeneous static magnetic fields.  The devices used were 500 gauss applied for  one hour to the affected shoulder.  The  magnets were of a  flexible concentric  field type, measuring 1.5 inches in diameter. The main outcomes were measured  using the McGill Pain Questionnaire and pressure algometry were compared.  Results using the McGill Pain Questionnaire  demonstrated significant decreases in stabbing (p&lt;0.02); sharp (p&lt;0.033);  and tender (p&lt;0.021).  There was also  demonstrated a significant decrease in the present pain intensity (p&lt;0.011).  Participants showed a non-significant  decrease (p&lt;0.55) on the visual analogue scale and pressure algometry was  non-significant (p&lt;0.885).</p>
	<p><a href="http://www.ncbi.nlm.nih.gov/pubmed/15162885" target="_blank">Panagos, A., et al. (2004)</a>. Treatment of myofascial  shoulder pain in the spinal cord injured population using static magnetic  fields: A case series. <em>Spinal Cord Med.  2004;27:138-142</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/15162885" target="_blank">PMID: 15162885</a>; </p>
	<p><a name="McDonald" id="McDonald"></a>McDonald, F (2004) in an unpublished study as part of an BPhty (Hons) degree at Griffith  University, conducted a placebo controlled trial on an individual with lateral  epicondylalgia. Pain free grip strength (PFGS) and pain pressure threshold  (PPT) were used to indicate localised analgesic effects. The PFGS decreased by  18.1% and 6.5% in the control and placebo conditions respectively, but  increased by 40% while wearing the active quadrapolar magnet. PPT measured at  the elbow decreased by 45.3% and 19.7% from baseline to post intervention  periods in the control and placebo conditions respectively (indicative of  hyperalgesia) but showed a 26% increase while wearing the active magnet  (indicative of analgesia).&nbsp;&nbsp; </p>
	<p>The study concluded that there is some evidence for  localised analgesic effects suggesting that a local mechanism may be  responsible and that the effects observed by the application of quadrapolar  magnets cannot be attributed to a placebo effect. </p>
	<p>McDonald, F. (2004). &quot;Effect of therapeutic  magnets on sympathetic nervous system outflow and pain related measures.  .&quot; <u>Unpublished</u>.</p>
	<p><a name="TA" id="TA"></a>Trigeminal Neuralgia<br />At the Lifestyle Therapies <a href="http://www.lifestyle100.com/site/services/physio/lifestyle-pain-clinic.html" target="_blank">pain clinic</a>,  there are a number of trigeminal neuralgia  sufferers referred there by local doctors and the MS Society physiotherapy  clinic in Brisbane. Of these cases, eight out of twelve were able to  significantly reduce or completely cease their medication after 7 days. Two  case studies were written up in the Lifestyle Therapies Medico’s Newsletter,  September, 2010.</p>
	<p><a href="http://www.lifestyle100.com/site/news/doctors-newsletter/Doctors%20Newsletter%2008%202010.pdf" target="_blank">Lifestyle Therapies Medico’s Newsletter, August 2010. A  novel and effective treatment for trigeminal neuralgia</a>. </p>


	<h3><a name="Rs" id="Rs"></a>REVIEWS (Click on the name link to go to summary):</h3>
	<p><a href="#Laakso-et-al-Static-Magnets-What-are-they-and-what-do-they-do">Laakso et al. (2009)</a> Static Magnets - What are they and what do they do. <em>Brazilian Journal of Physiotherapy: 2009;13(1):10-23</em>. <a href="http://dx.doi.org/10.1590%2FS1413-35552009005000013" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_eb_mclean_2001">McLean et al. (2001)</a> Static Magnetic Fields for the Treatment of Pain. <em>Epilepsy &amp; Behavior2: S74-S80 (2001)</em>.<a href="http://dx.doi.org/10.1006%2Febeh.2001.0211" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_ecam_colbert_2007">Colbert et al. (2009)</a> Static Magnetic Field Therapy: A Critical Review of Treatment Parameters. <em>Evid Based Complement Alternat Med: 6(2): 133-139.</em> <a href="http://www.ncbi.nlm.nih.gov/pubmed/18955243" target="_blank">PMID 18955243</a>. <a href="http://dx.doi.org/10.1093%2Fecam%2Fnem131" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_cmaj_pittler_2007">Pittler et al. (2007)</a> Static magnets for reducing pain: systematic review and meta-analysis of randomized trials. <em>CMAJ: 2007 Sep 25;177(7):736-42</em>.<a href="http://www.ncbi.nlm.nih.gov/pubmed/17893349" target="_blank"> PMID: 17893349</a>; <a href="http://dx.doi.org/10.1503%2Fcmaj.061344" target="_blank">doi</a>.</p>
	<p><a name="ASs" id="ASs"></a><strong>ANIMAL STUDIES</strong> (Click on the name link to go to summary):</p>
	<p><a href="blog/magnetic-therapy-2/new-research-on-static-magnetic-fields-and-tissue-repair.html" target="_blank">Jaberi et al. (2011).</a> A moderate-intensity static magnetic field enhances repair of cartilage damage in rabbits. <em>Arch Med   Res: 2011; 42(4): 268-273</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/21820604" target="_blank">PMID: 21820604</a>; <a href="http://dx.doi.org/10.1016%2Fj.arcmed.2011.06.004" target="_blank">doi</a>. </p>
	<p><a href="#researchpaper_Antal_laszlo_2009">Antal et al. (2009)</a> Exposure to Inhomogeneous Static Magnetic Field Ceases Mechanical Allodynia in Neuropathic Pain in Mice. <em>Bioelectromagnetics: 2009 Sep;30(6):438-45</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/19405037" target="_blank">PMID: 19405037</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20498" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_bems_laszlo_2007">Laszlo et al. (2007) </a>Optimization of static magnetic field parameters improves analgesic effect in mice. <em>Bioelectromagnetics 2007 Dec;28(8):615-27</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17654477" target="_blank">PMID: 17654477</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20341" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_ls_laszlo_2009">Laszlo et al. (2009)</a> 3 T homogeneous static magnetic field of a clinical MR significantly inhibits pain in mice. <em>Life Sciences: 2009 Jan 2;84(1-2):12-7</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/19000698" target="_blank">PMID:     19000698</a>; <a href="http://dx.doi.org/10.1016%2Fj.lfs.2008.10.009" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_ajphcp_morris_2007">Morris et al. (2008)</a> Acute Exposure to a Moderate Strength Static Magnetic Field Reduces Edema Formation In Rats. <em>Am J Physiol Heart Circ Physiol: 2008 Jan;294(1):H50-7</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17982018" target="_blank">PMID: 17982018</a>; <a href="http://dx.doi.org/10.1152%2Fajpheart.00529.2007" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_japplphys_morris_2007">Morris et al (2007)</a>. Chronic static magnetic field exposure alters microvessel enlargement resulting from surgical intervention. <em>J Appl Physiol : 2007 Aug;103(2):629-36</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17478604" target="_blank">PMID: 17478604</a>; <a href="http://dx.doi.org/10.1152%2Fjapplphysiol.01133.2006" target="_blank">doi</a>.</p>
	<p><span title="Epilepsy research."><a href="#researchpaper_er_mclean_2003">McLean et al. (2003)</a> </span>A static magnetic field modulates severity of audiogenic seizures and anticonvulsant effects of phenytoin in DBA/2 mice. <em>Epilepsy Res:2003 Jun-Jul;55(1-2):105-16</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12948620" target="_blank">PMID: 12948620</a>. <a href="http://dx.doi.org/10.1016%2FS0920-1211%2803%2900109-8" target="_blank">doi</a>.</p>

	<h3><a name="CSBSs" id="CSBSs"></a><strong>CELL STUDIES and BASIC SCIENCES</strong> (Click on the name link to go to summary):</h3>
	<p><a href="#Okano">Okano et al., (2012)</a> The Effects of Moderate-Intensity Gradient Static Magnetic Fields on Nerve Conduction. <em>Bioelectromagnetics. 2012 Mar 16.</em> <a href="http://www.ncbi.nlm.nih.gov/pubmed/22430817" target="_blank">PMID: 22430817</a>; <a href="http://dx.doi.org/10.1002/bem.21717" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_en_markov_2009">Markov M.S., (2009)</a> What need to be known about the therapy with static magnetic fields. <em>Environmentalist: (2009) 29:169–176</em>. <a href="http://dx.doi.org/10.1007%2Fs10669-009-9225-5" target="_blank">doi</a>.</p>
	<p><a href="#ColbertDC">Colbert et al. (2008)</a> Static Magnetic Field Therapy: Dosimetry Considerations. <em>J Altern Complement Med: 2008; 14(5). </em><a href="http://www.ncbi.nlm.nih.gov/pubmed/18532897" target="_blank">PMID: 18532897</a>; <a href="http://dx.doi.org/10.1089%2Facm.2007.0827" target="_blank">doi</a>. </p>
	<p><span title="Bioelectromagnetics."><a href="#researchpaper_bems_engstrom_2005">Engstrom et al. (2005)</a> </span>Devices for gradient static magnetic field exposure. <em>Bioelectromagnetics:2005 May;26(4):336-40</em><span class="style2">. </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/15832330" target="_blank">PMID: 15832330</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20098" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_bems_engstrom_2002">Engstrom et al. (2002) </a>Effects of non-uniform static magnetic fields on the rate of myosin phosphorylation. <em>Bioelectromagnetics: 2002 Sep;23(6):475-9</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12210566" target="_blank">PMID 12210566</a>; <a href="http://dx.doi.org/10.1002%2Fbem.10035" target="_blank">doi</a>.</p>
	<p><span title="Bioelectromagnetics."><a href="#researchpaper_bems_cavopol_1995">Cavapol et al. (1995)</a> </span> Measurement and analysis of static magnetic fields that block action potentials in cultured neurons. <em>Bioelectromagnetics.1995;16(3):197-206</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/7677796" target="_blank">PMID: 7677796</a>; <a href="http://dx.doi.org/10.1002%2Fbem.2250160308" target="_blank">doi</a>. </p>
	<p><span title="Bioelectromagnetics."><a href="#researchpaper_bems_mclean_1995">McLean et al. (1995)</a></span> Blockade of sensory neuron action potentials by a static magnetic field in the 10 mT range. <em>Bioelectromagnetics:1995;16(1):20-32</em><span class="style2">. </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/7748200" target="_blank">PMID: 7748200</a>; <a href="http://dx.doi.org/10.1002%2Fbem.2250160108" target="_blank">doi</a>.</p>
	<p><a href="#researchpaper_em_mclean_1991">McLean et al. (1991) </a> Effects of Steady Magnetic Fields on Action Potentials of Sensory Neurons in Vitro. <em>Environ Med: 1991; 8 (2): 36 - 45.</em> <a href="downloads/pub-effect-1.pdf" target="_blank">Download</a>.</p>
	<p><a name="Laakso-et-al-Static-Magnets-What-are-they-and-what-do-they-do" id="Laakso-et-al-Static-Magnets-What-are-they-and-what-do-they-do"></a><a href="downloads/Laakso-et-al-Static-magnets-What-are-they-and-what-do-they-do.pdf">Laakso et al (2009).</a> Static Magnets - What are they and what do they do? <em>Brazilian Journal of Physiotherapy: 2009;13(1):10-23</em>; <a href="http://dx.doi.org/10.1590%2FS1413-35552009005000013" target="_blank">doi</a><br />Can also be downloaded from<a href="http://www.scielo.br/pdf/rbfis/v13n1/011_09.pdf" target="_blank"> SciELO Brazil.</a><br />This is a good  place to start. It takes an honest look at static magnets, evaluates much of th e published research and describes and compares the common bipolar and quadrapolar magnets.</p>
	<p><a name="researchpaper_eb_mclean_2001" id="researchpaper_eb_mclean_2001"></a><a href="http://dx.doi.org/10.1006/ebeh.2001.0211" target="_blank">McLean et al. (2001)</a> Static Magnetic Fields for the Treatment of Pain. <em>Epilepsy &amp; Behavior2: S74-S80 (2001)</em>.<a href="http://dx.doi.org/10.1006/ebeh.2001.0211" target="_blank">doi</a>.<br /><span class="oneColLiqCtr">This </span>is a critical review of published data that supports potential therapeutic use of static magnetic field–generating devices. In particular it investigates the dosimetry and physiologic effects of quadrapolar magnetic devices. </p>
	<p><span title="Pediatric neurology."></span><a name="researchpaper_ecam_colbert_2007" id="researchpaper_ecam_colbert_2007"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/18955243" target="_blank">Colbert et al. (2009) </a>Static Magnetic Field Therapy: A Critical Review of Treatment Parameters. <em>Evid Based Complement Alternat Med 6(2): 133-139.</em> <a href="http://www.ncbi.nlm.nih.gov/pubmed/18955243" target="_blank">PMID 18955243</a>. <a href="http://dx.doi.org/10.1093%2Fecam%2Fnem131" target="_blank">doi</a>.<br /><span class="oneColLiqCtr">Can also be downloaded from<a href="http://www.hindawi.com/journals/ecam/2009/392815/abs/" target="_blank"> Evidence-based Complementary and Alternative Medicine.</a><br />This </span>paper is essentially a call for engineers, physicists and clinicians to continue to work together to optimise static magnetic field  dosage and treatment parameters for each clinical condition. It is also a response to the review by Pittler et al (see below) who reviewed </p>
	<p><a name="researchpaper_cmaj_pittler_2007" id="researchpaper_cmaj_pittler_2007"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/17893349" target="_blank">Pittler et al. (2007)</a> Static magnets for reducing pain: systematic review and meta-analysis of randomized trials. <em>CMAJ: 2007 Sep 25;177(7):736-42. </em><a href="http://www.ncbi.nlm.nih.gov/pubmed/17893349" target="_blank">PMID: 17893349</a>; <a href="http://dx.doi.org/10.1503%2Fcmaj.061344" target="_blank">doi</a>.<br /> Can also be downloaded from<a href="http://www.cmaj.ca/cgi/reprint/177/7/736.pdf" target="_blank"> Canadian Medical Association Journal</a><br />This is a classic case of conducting an investigation in an  attempt to reinforce  a preconceived position. In spite of all the available evidence (a fraction of which is available on this website), this article concludes that...&quot;the evidence does not support the use of static  magnets for pain relief, and such magnets therefore cannot be recommended as an effective treatment&quot;.</p>
	<p>Compare this paper's  summary of<a href="#researchpaper_apmr_segal_2001"> Segal et al (2001)</a>- &quot;No significant differences (to pain levels)&quot; to that of<a href="#researchpaper_bjp_laakso_2009"> Laakso et al (2009)</a>- &quot;Significantly less pain in treatment group compared to control group&quot;. One would wonder if they were reading from the same paper. <a href="#researchpaper_apmr_segal_2001"> Read it</a> yourself to form your own opinion.</p>
	<p><a name="researchpaper_Antal_laszlo_2009" id="researchpaper_Antal_laszlo_2009"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/19405037" target="_blank">Antal et al. (2009)</a></a> Exposure to Inhomogeneous Static Magnetic Field Ceases Mechanical Allodynia in Neuropathic Pain in Mice. <em>Bioelectromagnetics: 2009 Sep;30(6):438-45</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/19405037" target="_blank">PMID: 19405037</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20498" target="_blank">doi</a>.<br />Abstract Only. Summary:<br /> Inhomogeneous static magnetic field refers to a multipolar field gradient producing magnet as opposed to a simple bipolar homogenous magnetic field. The results suggest that exposure to iSMF cannot prevent the development of mechanical allodynia, but can inhibit processes that maintain the increased sensitivity to mechanical stimuli in neuropathic pain.</p>
	<p><a name="researchpaper_bems_laszlo_2007" id="researchpaper_bems_laszlo_2007"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/17654477" target="_blank">Laszlo et al. (2007)</a> </a>Optimization of static magnetic field parameters improves analgesic effect in mice. <em>Bioelectromagnetics 2007 Dec;28(8):615-27</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17654477" target="_blank">PMID: 17654477</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20341" target="_blank">doi</a>.    <br /> Abstract only.<br />Hungarian Academy of Science compares numerous static magnetic fields for their analgesic effect in mice. Finds that the quadrapolar array  achieves an analgesic effect of over 80% in the writhing test. Conclusion: As a non-drug, non-invasive, non-contact, non-pain, non-addictive method for analgesia with immediate and long-lasting effect based on the stimulus of the endogenous opioid network, the (quadrapolar) static magnetic field treatment may attract the attention of medical doctors, nurses, magnet therapists, veterinarians, physiotherapists, masseurs, and fitness trainers among others.</p>
	<p><a name="researchpaper_ls_laszlo_2009" id="researchpaper_ls_laszlo_2009"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/19000698" target="_blank">Laszlo et al. (2009)</a></a> 3 T homogeneous static magnetic field of a clinical MR significantly inhibits pain in mice. <em>Life Sciences: 2009 Jan 2;84(1-2):12-7</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/19000698" target="_blank">PMID:     19000698</a>; <a href="http://dx.doi.org/10.1016%2Fj.lfs.2008.10.009" target="_blank">doi</a>.<br /> Can also be downloaded from<a href="http://www.sciencedirect.com/science?_ob=PublicationURL&amp;_tockey=%23TOC%235109%232009%23999159998%23782161%23FLA%23&amp;_cdi=5109&amp;_pubType=J&amp;_auth=y&amp;_acct=C000050221&amp;_version=1&amp;_urlVersion=0&amp;_userid=10&amp;md5=748ee6095c7e0569c602503bf905fa34" target="_blank"> ScienceDirect</a><br /> This Hungarian study looked at  antinociceptive activity in the writhing test in mice and concluded that a 3 Tesla homogeneous static magnetic field  of a clinical magnetic resonance system induces a significant pain-inhibitory effect in the writhing test in mice.  In this experiment,  naloxone pretreatment reversed the pain-inhibitory effect of the static magnetic field confirming the hypothesis that an opioid component may be involved in the action. </p>
	<p><a name="researchpaper_ajphcp_morris_2007" id="researchpaper_ajphcp_morris_2007"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/17982018" target="_blank">Morris et al. (2008)</a></a> Acute Exposure to a Moderate Strength Static Magnetic Field Reduces Edema Formation In Rats. <em>Am J Physiol Heart Circ Physiol: 2008 Jan;294(1):H50-7</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17982018" target="_blank">PMID: 17982018</a>; <a href="http://dx.doi.org/10.1152%2Fajpheart.00529.2007" target="_blank">doi</a>.<br /> Can also be downloaded from<a href="http://ajpheart.physiology.org/cgi/content/full/294/1/H50" target="_blank"> American Journal of Physiology - Heart and Circulatory Physiology<br /></a>This study claims to be the first to demonstrate that acute, localized static magnetic field exposure of moderate field strength (5-100mT), when applied immediately after an inflammatory injury, can result in significant reduction of edema formation. While the study doesn't necessarily relate specifically to magnetic field gradients as they used bipolar magnets, it does a very good job at measuring the magnetic field dosage and treatment parameters and the results were significant. It would be interesting to compare results with a static magnetic field with a steep field gradient. There is also a take home message for users of magnetic therapy, <strong>as soon as you have an injury - apply your devices.</strong></p>
	<p><a name="researchpaper_japplphys_morris_2007" id="researchpaper_japplphys_morris_2007"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/17478604" target="_blank">Morris et al (2007)</a>. Chronic static magnetic field exposure alters microvessel enlargement resulting from surgical intervention. <em>J Appl Physiol : 2007 Aug;103(2):629-36</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/17478604" target="_blank">PMID: 17478604</a>; <a href="http://dx.doi.org/10.1152%2Fjapplphysiol.01133.2006" target="_blank">doi</a>.<br />This research looked at the effects of a localised static magnetic field on oedema after trauma in mice. The most significant reduction in arteriolar enlargement was manifested in the smallest vessels. As an example at day 7 sham treated vessels revealed venular enlargement of 91%, whereas magnet treated only 41%. This study blows away the common assumption that the healing of SMF's in induced by increasing the blood flow to the injured area. </p>
	<p><a name="researchpaper_er_mclean_2003" id="researchpaper_er_mclean_2003"></a><a href="http://www.ncbi.nlm.nih.gov/pubmed/12948620" target="_blank">McLean et al. (2003)</a></a> </span>A static magnetic field modulates severity of audiogenic seizures and anticonvulsant effects of phenytoin in DBA/2 mice. <em>Epilepsy Res:2003 Jun-Jul;55(1-2):105-16</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12948620" target="_blank">PMID: 12948620</a>. <a href="http://dx.doi.org/10.1016%2FS0920-1211%2803%2900109-8" target="_blank">doi</a>. Abstract only.</p>
	<p><a name="Okano" id="Okano"></a><a href="blog/magnetic-therapy-2/effects-of-moderate-static-magnetic-fields-on-nerve-conduction-and-its-relevance-to-q-magnet-therapy.html" target="_blank"><br />Okano et al., (2012)</a> The Effects of Moderate-Intensity Gradient Static Magnetic Fields on Nerve Conduction. <em>Bioelectromagnetics. 2012 Mar 16.</em> <a href="http://www.ncbi.nlm.nih.gov/pubmed/22430817" target="_blank">PMID: 22430817</a>; <a href="http://dx.doi.org/10.1002/bem.21717" target="_blank">doi</a>.<br />Nerve conduction velocity (NCV) was measured and compared within three groups, a control and a 0.21Tesla and 0.7Tesla iSMF. The researchers speculate that the action of moderate-intensity iSMF may act in a similar way to that of Na<sup>+</sup> channel-blocking anaesthetics.</p>
	<p><a name="researchpaper_en_markov_2009" id="researchpaper_en_markov_2009"></a><a href="downloads/Whatneedtobeknownaboutthetherapywithstaticmagneticfields.pdf"><br /></a>This article needs an applause:<br /><a href="http://dx.doi.org/10.1007/s10669-009-9225-5" target="_blank">Markov M.S., (2009)</a></a> What need to be known about the therapy with static magnetic fields. <em>Environmentalist: (2009) 29:169–176. </em><a href="http://dx.doi.org/10.1007/s10669-009-9225-5" target="_blank">doi</a>.<br /> Can also be downloaded from<a href="http://www.springerlink.com/content/qn25u106l4v047n3/fulltext.pdf" target="_blank"> Springer Science</a>.<br />In a critique of previous research, Marko Markov clearly articulates the inadequacies and describes what improvements need to be made if future research is to be credible and reproducible. It is also to a large degree a response to the study published in <a href="#Cepeda"> Anesthesia &amp; Analgesia</a> called Static Magnetic Therapy does not decrease pain or opioid requirements: A randomized double-blind trial.  </p>
	<p><a name="ColbertDC" id="ColbertDC"></a><a href="http://www.liebertonline.com/doi/abs/10.1089/acm.2007.0827?journalCode=acm" target="_blank">Colbert et al. (2008)</a></a> Static Magnetic Field Therapy: Dosimetry Considerations. <em>J Altern Complement Med: 2008; 14(5). </em><a href="http://www.ncbi.nlm.nih.gov/pubmed/18532897" target="_blank">PMID: 18532897</a>; <a href="http://dx.doi.org/10.1089%2Facm.2007.0827" target="_blank">doi</a>.<br />A recent systematic review of SMF trials for pain reduction concluded   that the evidence does not support the use of permanent magnets for pain   relief. We argue that this conclusion is unwarranted if the SMF dosage   was inadequate or inappropriate for the clinical condition treated.</p>
	<p><a name="researchpaper_bems_engstrom_2005" id="researchpaper_bems_engstrom_2005"></a><a href="downloads/Engstrom-Gradient-SMF-Bioelectromagnetics-2005.pdf">Engstrom et al. (2005)</a></a> </span>Devices for gradient static magnetic field exposure. <em>Bioelectromagnetics:2005 May;26(4):336-40</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/15832330" target="_blank">PMID: 15832330</a>; <a href="http://dx.doi.org/10.1002%2Fbem.20098" target="_blank">doi</a>.<br />Technical paper investigating dosimetry with field amplitude and gradient.</p>
	<p><a name="researchpaper_bems_engstrom_2002" id="researchpaper_bems_engstrom_2002"></a><a href="downloads/Pub-Phosph.pdf">Engstrom et al. (2002)</a> </a>Effects of non-uniform static magnetic fields on the rate of myosin phosphorylation. <em>Bioelectromagnetics: 2002 Sep;23(6):475-9</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/12210566" target="_blank">PMID 12210566</a>; <a href="http://dx.doi.org/10.1002%2Fbem.10035" target="_blank">doi</a>.This study investigates the effect of static magnetic field gradients on the rate of myosin phosphorylation. Findings confirmed that the most biological active region of the quadrapolar magnet was at the boundary between the poles where the magnetic field gradient was steepest. </p>
	<p><a name="researchpaper_bems_cavopol_1995" id="researchpaper_bems_cavopol_1995"></a><a href="downloads/Pub-Measurement.pdf">Cavapol et al. (1995)</a></a> </span> Measurement and analysis of static magnetic fields that block action potentials in cultured neurons. <em>Bioelectromagnetics.1995;16(3):197-206</em>. <a href="http://www.ncbi.nlm.nih.gov/pubmed/7677796" target="_blank">PMID: 7677796</a>; <a href="http://dx.doi.org/10.1002%2Fbem.2250160308" target="_blank">doi</a>. <br /> Findings suggested that the magnetic field gradient and not strength of the field was determining factor in action potential blockade.</p>
	<p><a name="researchpaper_bems_mclean_1995" id="researchpaper_bems_mclean_1995"></a><a href="downloads/pub-block-1.pdf">McLean et al. (1995)</a></span> </a>Blockade of sensory neuron action potentials by a static magnetic field in the 10 mT range. <em>Bioelectromagnetics:1995;16(1):20-32</em><span class="style2">. </span><a href="http://www.ncbi.nlm.nih.gov/pubmed/7748200" target="_blank">PMID: 7748200</a>; <a href="http://dx.doi.org/10.1002%2Fbem.2250160108" target="_blank">doi</a>.</p>
	<p><a name="researchpaper_em_mclean_1991" id="researchpaper_em_mclean_1991"></a><a href="downloads/pub-effect-1.pdf">McLean et al. (1991) </a></a> Effects of Steady Magnetic Fields on Action Potentials of Sensory Neurons in Vitro. <em>Environ Med: 1991; 8 (2): 36 - 45.</em> <a href="downloads/pub-effect-1.pdf" target="_blank">Download</a>.<br />This was a foundational study on the effects of static magnetic fields on sensory neurons, comparing the common bipolar magnets with multipolar magnets including the quadrapolar array. The comparison below is described.</p>
	<img src="images/arraycomp.jpg" />
</div>
				</div>
             </div>
            <div class="left_bottom_img"><img src="images/body_left_bottom_img.jpg" alt="" border="0"></div>
            </div>
          </div>
          
          <div class="body_right_area">
          <?php include("includes/yourpain.php");  ?>
          <?php include("includes/blog.php");      ?>
          </div>
        </div>
        </div>
    </section>
    <!--===================end section part===================--> 
    <!--===================Start footer part===================-->
    <footer>
      <?php include("includes/footer.php"); ?>
    </footer>
    <!--===================end footer part===================--> 
  </div>
</div>
</body>
</html>
