<?php include("admin/includes/include.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<?php include("includes/common_script.php"); ?>
<?php
if(file_exists("includes/metatags/meta-".basename($_SERVER['PHP_SELF']))) {
	include("includes/metatags/meta-".basename($_SERVER['PHP_SELF'])); 
} else {
	// ONCE META TAG NOT FOUND USE THE DEFAULT TITLE TAG
	echo '<title>Qmagnets</title>';
}
?>
<style>
.customContentStyle { }
.customContentStyle h3 { margin-bottom:5px; }
.customContentStyle p { line-height:150%; margin-bottom:16px; }
.customContentStyle ol { padding-left:30px; }
.customContentStyle ol li { margin-bottom:5px; }
</style>
</head>
<body>
<div id="main_area">
  <div class="main"> 
    <!--===================start header part===================-->
    <header>
      <div class="header_area">
        <?php include("includes/currency.php");  ?>
        <div class="nav_bg"> 
          <!--====================start nav part====================-->
          <?php include("includes/menu.php");  ?>
          <!--====================start nav part====================-->
           <?php include("includes/search.php");?>
        </div>
         <?php // include("includes/banner.php");  ?>
      </div>
    </header>
    <!--===================end header part===================--> 
    <!--===================Start section part===================-->
    <section>
    <div class="body_area">
         <div class="body_box">
          <div class="body_left_area">
          <div class="body_text_area">
            <div class="body_heading_bg">
              <h1>Comparing Magnetic Field Gradients of Static Magnets</h1>
            </div>
            <div class="about_body_text_box">
				<div id="cse-results" style="display: none;"></div><div class="body_left_text_area customContentStyle" id="static-content">
				
<p>We know from published studies that common bipolar magnets have very little affect on the nerve's messaging system; the firing of action potentials. In contrast, the steep field gradients running perpendicular to the local field vector generated by the quadrapolar, hexapolar and octapolar arrangements can have a dramatic effect, see <a href="how-Q-magnets-work.php">"How Q magnets work"</a>. </p>
<p>For those of us without PhD's in physics, magnetic field gradients can be a very complex topic. Steep field gradients (also called non-uniform or inhomogeneous fields) are generated when you have a combination of very strong magnetic fields and the close interaction of multiple magnetic poles. Looking at <a href="mri.php">the similarities of Q magnets and the discovery of the MRI which also utilises magnetic field gradients helps to explain a complex subject</a>. We have had a number of magnets tested in a quantum physics laboratory with the surface gradient values listed below and represented in colour charts. </p>
<p>Gradients Magnetic field gradients are determined by the rate of change of the strength of the field over distance. The greater the change, the greater the gradient which increases as opposite poles come closer together. </p>
<p> <img src="images/graphcopy_new.jpg" class="imgLeft" />Magnetic field gradients are the forces used in quantum physics that exert a translationalforce on both a stationary and moving charged particles such as a Sodium ion (Na+). This is in contrast to a uniform magnetic field such as from a bipolar magnet which exerts zero force on charged particles. The force/gradient relationship is represented by the formula... <img src="images/forceequation2.gif" alt="force equation" /> Force equation Where F is the force, <img src="images/gradient2.gif" alt="gradient" />Gradient is the gradient as a vector quantity and P is the magnetic potential. </p>
<p>Within the mammalian body there are numerous systems that involve the movement of charged particles, the obvious one is the active and passive transport of ions across the cell membrane through ion channels. Ion channels, particularly sodium channels in nerve cells are responsible for maintaining the resting membrane potential and for eliciting action potentials (the body's pain signal). </p>
<p>The transport of Sodium (Na+), Potassium (K+) and Calcium (Ca2+) ions across the cell membrane combine to generate the action potential. The research on Quadrapolar magnets suggests that the most likely mechanism is that the magnetic field gradient is altering nerve excitability as a result of changes in membrane permeability to sodium and calcium ions (<a href="downloads/pub-block-1.pdf">McLean et al., 1995</a>; <a href="downloads/Pub-Measurement.pdf">Cavopol et al., 1995</a>). </p>
<p>The steep field gradients generated by Quadrapolar magnets has an effect on charged particles that is not shared with the common bipolar magnets. While the mechanism of action is not conclusive, there are clearly additional effects at play. These effects can be observed with <a href="http://www.teachspin.com/instruments/magnetic_force/experiments.shtml">experiments such as this one.</a> </p>
<p>The first two images to the left below show how a dipole reacts in the presence of a uniform magnetic field. The image to the right shows the effects of a non-uniform field or magnetic field gradient. </p>

<div class="mfgwrap">
	<div class="mfgcolF">
		<img src="images/Field-Gradient-Uniform.jpg" alt="Field Gradient Uniform" />
		<div class="custommfg">
		<p>Uniform field does NOT exert translational force on dipole.</p>
		<p>A uniform magnetic field tends to orient a magnetic dipole.</p>
		</div>
	</div>
	
	<div class="mfgcolS">
		<img src="images/Field-Gradient-Uniform2.jpg" alt="Field Gradient Uniform" />
		<div class="custommfg">
		<p>Forces on North and South pole balance.</p>
		</div>
	</div>
	
	<div class="mfgcolT">
		<img src="images/Field-Gradient-Gradient.jpg" alt="Field Gradient Uniform" />
		<div class="custommfg">
		<p>A field gradient is required to exert a translational force on dipole.</p>
		<p>Figure shows a stronger force on the North pole than the South.</p>
		</div>
	</div>
</div>

<p>The coloured graphs below represent the rate of change of the magnetic field gradient measured in mT/mm (milliTesla per millimeter), 1 Tesla is equal to 10,000 Gauss. This is measuring the gradient that is perpendicular to the local field vector, i.e. running horizontally. <a href="http://qmagnets.com/mri.php">See the MRI page for more detail. </a></p>

<p><a href="images/MAGNET-SPECTRUM-SCALEQFCsmlr2.jpg"><img src="images/MAGNET-SPECTRUM-SCALEQFCsmlr2.jpg" class="imgLeft" width="200" /></a><br />The scale to the left uses colours to represent the magnetic field gradient, that is the rate of change of the strength of the field over distance - measured in mT/mm. <a href="images/MAGNET-SPECTRUM-SCALEQFCsmlr2.jpg">Click here for a larger image.</a><br /><br /><br />
You can see from the first two samples that we are comparing the <a href="products.php#QF28-6">QF28-6</a> magnet that contains the four magnetic poles within the one magnetic body with a competing product called Quadrabloc. <br /><br /><br />
At their peak, the Q magnet gradient is over 50% steeper than Quadrabloc. Not only is the Q magnet 50% more effective, but it's nearly half the size and hence much more comfortable to wear. </p>
<br />
<p>The next two samples are the quadrapolar magnet that was sold through Amway from 1999 to 2006 called MagnaBloc and a single centre charged round disc rare earth bipolar magnet.</p>


<p><a href="images/MAGNET-SPECTRUM-SCALEQFCsmlr2.jpg"><img src="images/MAGNETSPECTRUMSCALE2_FW.jpg" class="imgLeft" width="200" /></a>You can see that the MagnaBloc device has a relatively flat gradient when compared to the Q magnet. This is because the magnets contained within MagnaBloc were weaker and only 4mm thick. <br /><br />
Thicker and hence more powerful magnets will produce a steeper gradient. The <a href="products.php#QF28-6">QF28-6</a> magnet and magnets contained in the Quadrabloc were 6.0mm and 6.35mm (1/4 inch) thick respectively. <br /><br />
Finally the last sample was a bipolar magnet. The rate of change of the strength of the field never got past the first rung of the colour scale. In fact the rate of change only averaged a tiny 5 mT/mm at the surface of the magnet. <br /><br />
Since we know through the research that it's not the magnetic field strength, but the field gradient (steepness of the slope of the magnetic field) that is the determining factor in alleviating pain. The Q magnet is as far as we are aware the most effective therapeutic device for relieving pain on the market today.<br /><br />
You can also learn more about the comparison between Q magnets and Nikken's magnetic products at the <a href="nikken.php">"Q magnet/Nikken comparison"</a> page. </p>
<p>See the comparrison between different magnets with iron filings <a href="mri.php">on the MRI page</a>. </p>
<p>The design of a magnet is critical for specific applications. Magnetic field gradients are also important to cows, learn more on the <a href="why-magnet-design-matters.php">why magnet design matters</a> page. </p>


<h3 class="h3gold">Where else are magnetic field gradients being used in medicine?</h3>
<p>In nanotechnology by targeting magnetically loaded cell delivery which is localising cell therapy to specific target sites using strong field gradients. See research papers:</p>
<p>Deep magnetic capture of magnetically loaded cells for spatially targeted therapeutics. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6TWB-4XW6SXF-3&_user=10&_coverDate=03%2F31%2F2010&_rdoc=1&_fmt=high&_orig=gateway&_origin=gateway&_sort=d&_docanchor=&view=c&_searchStrId=1677729124&_rerunOrigin=scholar.google&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=fce042d65a3d94506ee4118a29728e84&searchtype=a">Biomaterials 31 (2010) 2130-2140</a></p>
<p>High field gradient targeting of magnetic nanoparticle-loaded endothelial cells to the surfaces of steel stents. <a href="http://www.pnas.org/content/105/2/698.abstract" target="_blank">PNAS (2008) 105(2) 698</a> </p>


<div class="divCenter"><p>Click on the Order Now button below to place your order. </p>
<a href="products.php"><img src="images/order-now-button.gif" alt="Order Now" /></a></div>

<style>
.h3gold { color:#FFDD77; }
.divCenter { text-align:center; }
.custommfg { margin-top:10px; border-top:1px solid #444; padding:10px; }
.mfgwrap { overflow:hidden; text-align:left; }
.mfgwrap img { width:100%; }
.mfgwrap .mfgcolF { width:180px; float:left; margin-right:6px; }
.mfgwrap .mfgcolS { width:180px; float:left; margin-right:6px; }
.mfgwrap .mfgcolT { width:180px; float:left; }
</style>
				
				</div>
             </div>
            <div class="left_bottom_img"><img src="images/body_left_bottom_img.jpg" alt="" border="0"></div>
            </div>
          </div>
          
          <div class="body_right_area">
          <?php include("includes/yourpain.php");  ?>
          <?php include("includes/blog.php");      ?>
          </div>
        </div>
        </div>
    </section>
    <!--===================end section part===================--> 
    <!--===================Start footer part===================-->
    <footer>
      <?php include("includes/footer.php"); ?>
    </footer>
    <!--===================end footer part===================--> 
  </div>
</div>
</body>
</html>
