<?php include("admin/includes/include.php"); ?>

<!DOCTYPE HTML>
<html>
<head>
<?php include("includes/common_script.php"); ?>
<?php
if(file_exists("includes/metatags/meta-".basename($_SERVER['PHP_SELF']))) {
	include("includes/metatags/meta-".basename($_SERVER['PHP_SELF'])); 
} else {
	// ONCE META TAG NOT FOUND USE THE DEFAULT TITLE TAG
	echo '<title>Qmagnets</title>';
}
?>
</head>
<body>
<div id="main_area">
  <div class="main"> 
    <!--===================start header part===================-->
    <header>
      <div class="header_area">
        <?php include("includes/currency.php");  ?>
        <div class="nav_bg"> 
          <!--====================start nav part====================-->
          <?php include("includes/menu.php");  ?>
          <!--====================start nav part====================-->
           <?php include("includes/search.php");?>
        </div>
         <?php // include("includes/banner.php");  ?>
      </div>
    </header>
    <!--===================end header part===================--> 
    <!--===================Start section part===================-->
    <section>
    <div class="body_area">
         <div class="body_box">
          <div class="body_left_area">
          <div class="body_text_area">
            <div class="body_heading_bg">
              <h1>Hexapole takes medical grade magnets into a new era</h1>
            </div>
            <div class="about_body_text_box">
              <p>November 1,  2009</p>
              <p><br />
                &quot;Q magnets have made a further break through in the design and development
                of therapeutic magnets for the treatment of pain&quot; says Managing Director James
                Hermans.</p>
              <p>&nbsp;</p>
              <p>There is a significant body of <a href="magnetic-therapy-relevant-research.php?&id=magnetic-therapy-published-research">research</a> that
                 demonstrates the effect static magnets with steep field gradients have
                on nerve fibres. Steep field gradients are generated by the interaction of multiple
                poles in close proximity. </p>
              <p>&nbsp;</p>
              <p>The pioneering work by inventor and neurologist Dr Robert Holcomb while at Vanderbilt
                Medical University lead the way in this field. Dr Holcomb's original design was
                comprised of four bipolar disc magnets arranged in an alternating +/-/+/- quadrapolar
                array (see below). The <a href="downloads/Pub-TreatPain.pdf" target="_blank">steepest
                part of the field gradient</a> was where the four bipolar
                magnets made contact. Due to the physical constraints
                of the round discs it's not practical to arrange six bipolar magnets into a hexapole
                arrangement. </p>
              <p>&nbsp;</p>
              <p>In 2008, utilising advanced techniques in magnetisation and a new design, James
                and Dianne Hermans developed a rare earth, neodymium Quadrapolar magnet within
                the one magnetic body. This meant that the steep field gradient was now generated
                along the entire boundary of the four poles.</p>
              <p>&nbsp;</p>
              <p>Now in 2009, the Hexapole design  has arrived - <a href="products.php#ProHS">ProH</a>.
                Instead of four alternating poles and four steep field gradient zones, there are
                now six. The consequence for the patient in pain is that there are 6 instead of
                4 active areas of the magnet so there is a greater chance that the field gradient
                will penetrate the over-active and abnormally firing C-fibres that are eliciting
                the pain signal. </p>
              <p>&nbsp;</p>
              <p>Common bipolar
              magnets put out a uniform field with a negligible <a href="magnetic-field-gradients.php">field
              gradient</a>. While bipolar magnets
                might be having different effects on the body, <a href="magnetic-therapy-relevant-research.php?&id=magnetic-therapy-published-research#researchpaper_em_mclean_1991">the
                research shows</a> they have a minimal
                effect on interrupting the pain signal on afferent C-fibres. </p>
              <p>&nbsp;</p>
              <p>James said...&quot;While we have yet to conduct clinical trials on the hexapole
                design, we are reasonably certain that the greater area of field gradients will
                have a more profound effect on  nerves and reducing pain. Initial trials with some
                of the physiotherapists and professional athletes we have provided them to has
                certainly confirmed this. There was also the case of the marathon runner with the <a href="http://qmagnets.com/blog/pain-testimonies/leg-pain/tibia-stress-fracture-threatens-competing-in-marathon-%E2%80%93-no-worries-with-q-magnets.html">tibia
                stress fracture</a>&quot;.</p>
              <p>&nbsp;</p>
              <p>END</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <div id="caption">Q magnet comparisons</div>

              <table  border="2" cellpadding="2" bordercolor="#000000" bgcolor="#FFFFFF" id="tableComapre">
              
                <tr>
                  <td><strong>Original Design by Dr Holcomb at Vanderbilt (1989).</strong></td>
                  <td><strong>Q magnet Quadrapole Design (2007)</strong></td>
                  <td><strong>Q magnet Hexapole design (2009)</strong></td>
                </tr>
                <tr>
                  <td ><div align="center"><img src="images/1QMagnetP.jpg" alt="Magna Bloc" height="160" /></div></td>
                  <td><div align="center"><img src="images/Quadrapole.jpg" alt="Quadrapolar" height="160" /></div></td>
                  <td><div align="center"><img src="images/Hexapole.jpg" alt="Hexapole" height="160"/></div></td>
                </tr>
              </table>  
            </div>
            <div class="left_bottom_img"><img src="images/body_left_bottom_img.jpg" alt="" border="0"></div>
            </div>
          </div>
          
          <div class="body_right_area">
          <?php include("includes/yourpain.php");  ?>
          <?php include("includes/blog.php");      ?>
          </div>
        </div>
        </div>
    </section>
    <!--===================end section part===================--> 
    <!--===================Start footer part===================-->
    <footer>
      <?php include("includes/footer.php"); ?>
    </footer>
    <!--===================end footer part===================--> 
  </div>
</div>
</body>
</html>
